# Google Cloud Build configuration for auto-deployment from GitHub
# This file triggers automatically when you push to GitHub (after connecting repo)

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cognivoice-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cognivoice-backend:latest'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cognivoice-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cognivoice-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cognivoice-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cognivoice-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/cognivoice-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cognivoice-backend:latest'

# Build timeout (PyTorch installation takes time)
timeout: '1800s'
